version: "2.3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: "redis:3.2-alpine"
    command: redis-server
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rails:
    # container_name: rails
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: password
      VIRTUAL_HOST: turbochat.docker
      # VIRTUAL_PORT: 3000
    depends_on:
      - postgres
      - redis
